### ISSUE TITLE
Login Doesnt Direct Immediately

### ISSUE THREAD

**Issue by CyrusVatandoost** [CyrusVatandoost/warehouse#16]
When signing in, the page does not immediately direct to WareHouse's home page. One must refresh before doing that.

**Comment by christalon** [comment]
Oh right, I put the redirection on when there is a successful signup and there will be a notification below. When they close the notification, it redirects.

This isn't what I have planned, though I want to make it automatically redirect once there is a successful signup, and also add a back button.
