### ISSUE TITLE
Add Forms in Contact Us Page

### ISSUE THREAD

**Issue by CyrusVatandoost** [CyrusVatandoost/warehouse#20]
A form to email or message the organization's head must be made. Please make a form for it inside /warehouse/contact.php.

**Comment by CyrusVatandoost** [comment]
Test Commetn

**Comment by Marlcelo** [comment]
What should be the fields?

So far, I have the following:

>Name
>Topic
>Message

**Comment by CyrusVatandoost** [comment]
Add email address also! You can start na

**Comment by Marlcelo** [comment]
Alrighty! Thanks bai. On it!

**Comment by CyrusVatandoost** [comment]
@Marlcelo it's good but could you improve the UI look of it? You can get generated codes from Layoutit! http://www.layoutit.com/build# to easily create UI.  Here's an example of how i want it to look like: If you have other ideas of improving the design, do suggest it to me!

![image](https://user-images.githubusercontent.com/22030882/33081357-1feac288-cf15-11e7-83c7-aabc9cbe51e3.png)

**Comment by xandraureta** [comment]
Hi! You can check this design too :)
![image](https://user-images.githubusercontent.com/31879731/33087977-2f5b5806-cf27-11e7-85c0-14c45b6fa8cf.png)

**Comment by CyrusVatandoost** [comment]
Nice! But the contact details are redundant because it's almost exactly the same from the footer. Either we remove the contact details or we remove the footer for the contact us page.

![image](https://user-images.githubusercontent.com/22030882/33144492-3e9a6056-cff8-11e7-86ac-988c99005f1d.png)
