### ISSUE TITLE
Make WareHouse Logo

### ISSUE THREAD

**Issue by CyrusVatandoost** [CyrusVatandoost/warehouse#22]

**Comment by CyrusVatandoost** [comment]
Once this has been made, we can start adding the logo as icons inside the project.

**Comment by danielflachica** [comment]
Simple logo idea. Colors are definitely not final, just a suggestion for the design: 
![icon_warehouse](https://user-images.githubusercontent.com/25632004/33041631-f3019bac-ce79-11e7-8ef7-bbc439164484.png)

**Comment by CyrusVatandoost** [comment]
Oooh pretty. Could you make it a little taller para it would fit a square? Just try lang
