### ISSUE TITLE
[UI Element]  Back Button for the Project Section

### ISSUE THREAD

**Issue by xandraureta** [CyrusVatandoost/warehouse#5]
![capture](https://user-images.githubusercontent.com/31879731/32699719-263865b8-c7f5-11e7-987e-8ec45c0d24c7.JPG)

Project Section is by page
Problem : User can't go back from the page
Solution : Back Button :D

**Comment by CyrusVatandoost** [comment]
That's a great idea! I will implement that soon! Thank you for telling us this.

**Comment by danielflachica** [comment]
k
